apiVersion: apps/v1
kind: Deployment
metadata:
  name: wbparser-service
spec:
  selector:
    matchLabels:
      app: wbparser-service
  replicas: 1
  template:
    metadata:
      labels:
        app: wbparser-service
    spec:
      containers:
        - name: wbparser-service
          image: sellspasibo/wbparser-service
          ports:
          - containerPort: 80
          tty: true
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4